package snap

const (
	PRIVPKCS1 = "RSA PRIVATE KEY"
	PRIVPKCS8 = "PRIVATE KEY"

	PUBPKCS1    = "RSA PUBLIC KEY"
	PUBPKCS8    = "PUBLIC KEY"
	CERTIFICATE = "CERTIFICATE"

	KEY_SIZE_2048 = 2048
	KEY_SIZE_4096 = 4096
)
